### ISSUE TITLE
QC doesn't run: NoClassDefFoundError

### ISSUE THREAD

**Issue by DeniseSl22** [bridgedb/BridgeDb#132]
Just tried to run the QC script on a metabolite_mapping file from the command line, however I got the following exception:

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/col                                                            lect/Multiset
        at org.bridgedb.tools.qc.BridgeQC.main(BridgeQC.java:345)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Multiset
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 1 more

```

I'm not sure what is causing this error; the new mapping files seems to work fine in PathVisio.

The QC.jar I'm using can be found [here](https://github.com/bridgedb/InteractionDB/tree/master/lib) (couldn't build a fresh one, reopened issue #90 for that).
The Metabolite mapping file [here](https://jenkins.bigcat.unimaas.nl/job/Metabolite%20ID%20Mapping%20Database/ws/hmdb_chebi_wikidata_metabolites.bridge) .

**Comment by The-Marvex** [comment]
I'll start working on this ASAP

**Comment by egonw** [comment]
I think this is because it expects the Google library to be install in ~/.m2/ via Maven...

**Comment by egonw** [comment]
@DeniseSl22, does it work after you ran `mvn -Dmaven.test.skip=true  clean install`?
