### ISSUE TITLE
IMS link set build failing

### ISSUE THREAD

**Issue by ariutta** [bridgedb/BridgeDb#58]
[datasources.txt](https://cdn.rawgit.com/ariutta/1c2c8179467e16823383bbcdb1fcd108/raw/9cb860d90bab61de8d6ae45a926df53ee1525956/pretty-tsv-viewer.html?source=https%3A%2F%2Frawgit.com%2Fbridgedb%2FBridgeDb%2Fmaster%2Forg.bridgedb.bio%2Fresources%2Forg%2Fbridgedb%2Fbio%2Fdatasources.txt) has an issue with the `uri` column, and it's causing the IMS link set build to fail. According to [datasources_headers.txt](https://cdn.rawgit.com/ariutta/1c2c8179467e16823383bbcdb1fcd108/raw/9cb860d90bab61de8d6ae45a926df53ee1525956/pretty-tsv-viewer.html?source=https%3A%2F%2Frawgit.com%2Fbridgedb%2FBridgeDb%2Fmaster%2Forg.bridgedb.bio%2Fresources%2Forg%2Fbridgedb%2Fbio%2Fdatasources_headers.txt), the `uri` column is:

> Official URI for datasource (e.g., from miriam); or repeat of system_code if unknown or unregistered

[According to miriam](https://www.ebi.ac.uk/miriam/main/datatypes/MIR:00000005), the `uri` value for both Swissprot and Trembl is `urn:miriam:uniprot` (see also issue #17). [bridgedbjs](npmjs.com/package/bridgedb) needs to get the miriam urn for both Swissprot and Trembl, and it was getting it from datasources.txt. But the build for the IMS link set fails when both Swissprot and Trembl have `uri` value `uniprot`.

[This commit](https://github.com/bridgedb/BridgeDb/commit/bbb29bdf6a083f5d0f17410367d65381e16df556) is a temporary patch so the IMS link sets can build, but bridgedbjs won't work with that patch.

Should miriam have different uris for Swissprot and Trembl, or should the IMS link sets accept that the miriam urns are the same for both?

BDB/IMS link set stack trace:
```
Loading linkset file:///staging/linksets2/conceptwiki/www_uniprot_org_uniprot-gene.ttl
        Using File: /staging/linksets2/conceptwiki/www_uniprot_org_uniprot-gene.ttl
Error handling: (http://www.conceptwiki.org/concept/5fa40ec7-c73f-4810-a5c7-3743970b02ec, http://www.w3.org/2004/02/skos/core#exactMatch, http://www.uniprot.
org/uniprot/O14329)
org.bridgedb.utils.BridgeDBException: Uri http://www.uniprot.org/uniprot/O14329 maps to two different regex patterns http://www.uniprot.org/uniprot/$id (^([A
-N,R-Z][0-9][A-Z][A-Z, 0-9][A-Z, 0-9][0-9])|([O,P,Q][0-9][A-Z, 0-9][A-Z, 0-9][A-Z, 0-9][0-9])(\.\d+)?|([A-N,R-Z][0-9][A-Z][A-Z, 0-9][A-Z, 0-9][0-9][A-Z][A-Z,
 0-9][A-Z, 0-9][0-9])$) for DataSource S and http://www.uniprot.org/uniprot/$id (^([A-N,R-Z][0-9]([A-Z][A-Z, 0-9][A-Z, 0-9][0-9]){1,2})|([O,P,Q][0-9][A-Z, 0-
9][A-Z, 0-9][A-Z, 0-9][0-9])(\.\d+)?$) for DataSource Sp
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.simontuffs.onejar.Boot.run(Boot.java:340)
        at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: org.bridgedb.utils.BridgeDBException: Error loading
        at uk.ac.manchester.cs.openphacts.ims.loader.RunLoader.main(RunLoader.java:241)
        ... 6 more
Caused by: org.bridgedb.utils.BridgeDBException: Error parsing /staging/linksets2/conceptwiki/www_uniprot_org_uniprot-gene.ttl Error inserting statement (htt
p://www.conceptwiki.org/concept/5fa40ec7-c73f-4810-a5c7-3743970b02ec, http://www.w3.org/2004/02/skos/core#exactMatch, http://www.uniprot.org/uniprot/O14329)
        at org.bridgedb.uri.loader.RdfParser.parse(RdfParser.java:71)
        at uk.ac.manchester.cs.openphacts.ims.loader.LinksetLoader.load(LinksetLoader.java:92)
        at uk.ac.manchester.cs.openphacts.ims.loader.LinksetLoader.load(LinksetLoader.java:69)
        at uk.ac.manchester.cs.openphacts.ims.loader.RunLoader.loadLinkset(RunLoader.java:102)
        at uk.ac.manchester.cs.openphacts.ims.loader.RunLoader.main(RunLoader.java:225)
        ... 6 more
Caused by: org.openrdf.rio.RDFHandlerException: Error inserting statement (http://www.conceptwiki.org/concept/5fa40ec7-c73f-4810-a5c7-3743970b02ec, http://www.w3.org/2004/02/skos/core#exactMatch, http://www.uniprot.org/uniprot/O14329)
        at org.bridgedb.uri.loader.LinkHandler.insertUriMapping(LinkHandler.java:101)
        at org.bridgedb.uri.loader.LinkHandler.handleStatement(LinkHandler.java:73)
        at org.bridgedb.uri.loader.LinksetHandler.processFirstStatement(LinksetHandler.java:122)
        at org.bridgedb.uri.loader.LinksetHandler.handleStatement(LinksetHandler.java:76)
        at uk.ac.manchester.cs.openphacts.ims.loader.handler.ImsHandler.handleStatement(ImsHandler.java:55)
        at org.openrdf.rio.turtle.TurtleParser.reportStatement(TurtleParser.java:1062)
        at org.openrdf.rio.turtle.TurtleParser.parseObject(TurtleParser.java:476)
        at org.openrdf.rio.turtle.TurtleParser.parseObjectList(TurtleParser.java:399)
        at org.openrdf.rio.turtle.TurtleParser.parsePredicateObjectList(TurtleParser.java:371)
        at org.openrdf.rio.turtle.TurtleParser.parseTriples(TurtleParser.java:356)
        at org.openrdf.rio.turtle.TurtleParser.parseStatement(TurtleParser.java:246)
        at org.openrdf.rio.turtle.TurtleParser.parse(TurtleParser.java:203)
        at org.bridgedb.uri.loader.RdfParser.parse(RdfParser.java:67)
        ... 10 more
Caused by: org.bridgedb.utils.BridgeDBException: No SourceURIPattern regstered for mappingSetId 0
        at org.bridgedb.sql.SQLUriMapper.insertUriMapping(SQLUriMapper.java:983)
        at org.bridgedb.uri.loader.LinkHandler.insertUriMapping(LinkHandler.java:99)
        ... 22 more
```

**Comment by egonw** [comment]
@AlexanderPico, @ariutta, @mkutmon, is there a reason why we should not just remove Sp from the the datasources.txt? Are we actually using both Trembl and SwissProt?

**Comment by ariutta** [comment]
@egonw, there are some pathways at WikiPathways that currently use SwissProt.

The simplest way to model this:
* Trembl is the datasource that mints identifiers
* SwissProt is a QA tag for those Trembl identifiers but is not a source of identifiers in its own right

Can we make our data reflect that model? We can easily run a script to convert SwissProt to Trembl for WikiPathways. We'd also need to update PathVisio-Java so we don't get more SwissProt after we run that script.

![image](https://user-images.githubusercontent.com/1296771/35821360-a485a1a6-0a5d-11e8-9ef0-e251e455a20b.png)

**Comment by ariutta** [comment]
Maybe the content for that dropdown comes from datasources.txt?

**Comment by egonw** [comment]
Closed by https://github.com/bridgedb/BridgeDb/commit/192a18f2ee626279b0845a597b5861f02fe8e521

I will make a test right now that reports remaining use of Uniprot-SwissProt.
